kind: Service
apiVersion: v1
metadata:
  name: grafana-ingress
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana-ingress
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: grafana-ingress
  ports:
    - name: http
      port: 80
      targetPort: 8080
